### PR TITLE
Finish docs

### PR DESCRIPTION
**Pull request by julia-martin**
- Added the fonts for our theme and changed the colors on the sidebar to match the Waypost aesthetic
- Finished adding most recent version of documentation
- Added screenshots and screen recordings where relevant

*Note: Since the docs are in markdown we can only add images to them, so the screen recordings had to be converted to gif's first in order to work

### CODE REVIEW

**Comment by seanrichardson95** [comment]
Can we make these arrows white for the "light" version of the app? 
image

**Comment by seanrichardson95** [comment]
Can we get rid of this button? 
image
It seems to be at the end of every page.

**Comment by seanrichardson95** [comment]
Disclaimer: I don't think that this is a priority (since we have the write-up), but in case we want to touch stuff up in the case we finish early...

It'd be nice if all the buttons up here worked. The Home button and the button on the end link to the pages, but the middle button (in this case reading "SDK") doesn't do anything when clicked. 
image

**Comment by seanrichardson95** [comment]
Wow, great job Julia! Those gifs look really awesome! I didn't really look at the wording of everything since we did a lot of that in Notion, but the look and feel of the docs are great! My only problems are the first two I commented above. After those are fixed let's merge!

**Comment by julia-martin** [comment]
Sure, I made the changes for the first two things you mentioned, but for the last one with the hierarchy thing I'm not sure how to change that. It's just how the docs are structured in Docusaurus because I have a folder for SDK so it's saying that doc is within the SDK folder.

**Pull request merged**
