### PR TITLE
Documentation Customization

### PR DESCRIPTION
**Pull request by julia-martin**
Started customizing the Docusaurus config to use Waypost information instead of the defaults, added our turquoise and purple colors to the CSS, and also added a few parts of our documentation just to see how it works.

We'll still need to do some more customization but wanted to get at least some parts updated for now.

### CODE REVIEW

**Comment by seanrichardson95** [comment]
Wow! This is awesome! Looks so good! I think the only thing I would change is to use the version of our logo with out the letters in it, since this doesn't render very well 
image

I'm pushing a commit with the logos without letters. Lmk what you think!

**Comment by seanrichardson95** [comment]
Here's what it looks like now:
image
image

**Comment by julia-martin** [comment]
Awesome, thanks for changing that! For some reason when I tried it they always looked weird on either light mode or dark mode. Glad you got it to work!

**Comment by seanrichardson95** [comment]
> Awesome, thanks for changing that! For some reason when I tried it they always looked weird on either light mode or dark mode. Glad you got it to work!

Yeah, I used two different logos, one for light and one for dark. 
image

**Pull request merged**
